// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: humans.proto

package routeguide

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ID) Reset() {
	*x = ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_humans_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_humans_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_humans_proto_rawDescGZIP(), []int{0}
}

func (x *ID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Human struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname  string `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname   string `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Age        int32  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Likespizza bool   `protobuf:"varint,5,opt,name=likespizza,proto3" json:"likespizza,omitempty"`
}

func (x *Human) Reset() {
	*x = Human{}
	if protoimpl.UnsafeEnabled {
		mi := &file_humans_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Human) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Human) ProtoMessage() {}

func (x *Human) ProtoReflect() protoreflect.Message {
	mi := &file_humans_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Human.ProtoReflect.Descriptor instead.
func (*Human) Descriptor() ([]byte, []int) {
	return file_humans_proto_rawDescGZIP(), []int{1}
}

func (x *Human) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Human) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *Human) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *Human) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Human) GetLikespizza() bool {
	if x != nil {
		return x.Likespizza
	}
	return false
}

var File_humans_proto protoreflect.FileDescriptor

var file_humans_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x68, 0x75, 0x6d, 0x61, 0x6e, 0x73, 0x22, 0x14, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x83, 0x01, 0x0a,
	0x05, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61,
	0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x70, 0x69, 0x7a, 0x7a, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x70, 0x69, 0x7a,
	0x7a, 0x61, 0x32, 0x5d, 0x0a, 0x06, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x73, 0x12, 0x27, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x12, 0x0a, 0x2e, 0x68, 0x75, 0x6d, 0x61, 0x6e,
	0x73, 0x2e, 0x49, 0x44, 0x1a, 0x0d, 0x2e, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x73, 0x2e, 0x48, 0x75,
	0x6d, 0x61, 0x6e, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48,
	0x75, 0x6d, 0x61, 0x6e, 0x12, 0x0d, 0x2e, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x73, 0x2e, 0x48, 0x75,
	0x6d, 0x61, 0x6e, 0x1a, 0x0a, 0x2e, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x73, 0x2e, 0x49, 0x44, 0x22,
	0x00, 0x42, 0x68, 0x0a, 0x1b, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x67, 0x75, 0x69, 0x64, 0x65,
	0x42, 0x0f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x47, 0x75, 0x69, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x36, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x65,
	0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x67, 0x75, 0x69, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_humans_proto_rawDescOnce sync.Once
	file_humans_proto_rawDescData = file_humans_proto_rawDesc
)

func file_humans_proto_rawDescGZIP() []byte {
	file_humans_proto_rawDescOnce.Do(func() {
		file_humans_proto_rawDescData = protoimpl.X.CompressGZIP(file_humans_proto_rawDescData)
	})
	return file_humans_proto_rawDescData
}

var file_humans_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_humans_proto_goTypes = []interface{}{
	(*ID)(nil),    // 0: humans.ID
	(*Human)(nil), // 1: humans.Human
}
var file_humans_proto_depIdxs = []int32{
	0, // 0: humans.Humans.GetHuman:input_type -> humans.ID
	1, // 1: humans.Humans.CreateHuman:input_type -> humans.Human
	1, // 2: humans.Humans.GetHuman:output_type -> humans.Human
	0, // 3: humans.Humans.CreateHuman:output_type -> humans.ID
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_humans_proto_init() }
func file_humans_proto_init() {
	if File_humans_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_humans_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_humans_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Human); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_humans_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_humans_proto_goTypes,
		DependencyIndexes: file_humans_proto_depIdxs,
		MessageInfos:      file_humans_proto_msgTypes,
	}.Build()
	File_humans_proto = out.File
	file_humans_proto_rawDesc = nil
	file_humans_proto_goTypes = nil
	file_humans_proto_depIdxs = nil
}
